# Generated by Django 3.1.4 on 2020-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_lyzd_project_sys_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyzd_Interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_name_en', models.CharField(max_length=100, verbose_name='接口英文名称')),
                ('interface_name_zh', models.CharField(max_length=100, verbose_name='接口中文名称')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('authentication', models.CharField(max_length=100, verbose_name='认证')),
                ('encryption', models.CharField(max_length=100, verbose_name='加密的接口url')),
                ('decrypt', models.CharField(max_length=100, verbose_name='解密的接口url')),
                ('delete_flag', models.CharField(max_length=5, verbose_name='删除标志')),
                ('create_user', models.CharField(max_length=100, verbose_name='创建用户')),
                ('modify_user', models.CharField(max_length=100, verbose_name='修改用户')),
                ('requestParameterType', models.CharField(max_length=50, verbose_name='修改用户')),
                ('content', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
            },
        ),
        migrations.DeleteModel(
            name='Lyzd_Project',
        ),
    ]
