# Generated by Django 3.1.4 on 2020-12-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20201214_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('status', models.IntegerField(max_length=1, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
            },
        ),
        migrations.AddField(
            model_name='lyzd_interface',
            name='Project_id',
            field=models.ForeignKey(max_length=1024, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.project', verbose_name='项目id'),
        ),
    ]
