# Generated by Django 3.1.4 on 2020-12-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20201214_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100, verbose_name='接口英文名称')),
                ('create_user', models.CharField(max_length=100, verbose_name='创建用户')),
                ('modify_user', models.CharField(max_length=100, verbose_name='修改用户')),
                ('status', models.CharField(max_length=50, verbose_name='修改用户')),
                ('content', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('testers', models.CharField(max_length=100, verbose_name='接口英文名称')),
                ('developer', models.CharField(max_length=100, verbose_name='接口英文名称')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Project', models.ForeignKey(max_length=1024, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.project', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '模块表',
                'verbose_name_plural': '模块信息',
            },
        ),
    ]
