# Generated by Django 3.1.4 on 2020-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_sys_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_project',
            name='status',
            field=models.CharField(max_length=5, verbose_name='状态'),
        ),
    ]
