# Generated by Django 3.1.4 on 2020-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_auto_20201214_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_model',
            name='developer',
            field=models.CharField(max_length=100, verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='sys_model',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='sys_model',
            name='status',
            field=models.CharField(max_length=5, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sys_model',
            name='testers',
            field=models.CharField(max_length=100, verbose_name='测试人员'),
        ),
    ]
